# Generated by Django 3.1.7 on 2021-02-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peaples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('secondName', models.CharField(max_length=25, verbose_name='Имя')),
                ('thirdName', models.CharField(max_length=25, verbose_name='Очество')),
                ('school', models.CharField(max_length=25, verbose_name='Школа')),
                ('rayon', models.CharField(max_length=25, verbose_name='Район')),
                ('login', models.CharField(max_length=25, verbose_name='логин')),
                ('role', models.CharField(max_length=10, verbose_name='Ученик/Учитель')),
                ('password', models.CharField(max_length=10, verbose_name='пароль')),
                ('classes', models.CharField(blank=True, max_length=2, verbose_name='Класс ')),
                ('passwordParents', models.CharField(blank=True, max_length=10, verbose_name='Пароль для родителей')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
                'ordering': ('login',),
            },
        ),
        migrations.DeleteModel(
            name='Peaple',
        ),
    ]
