# Generated by Django 3.1.7 on 2021-02-25 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_schools'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schools',
        ),
    ]
