# Generated by Django 3.1.7 on 2021-02-25 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestsHelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subject', models.CharField(choices=[('Fundamentals of Life Safety', 'ОБЖ'), ('chemistry', 'химия'), ('technology', 'технология'), ('drawing', 'Черчение'), ('informatics', 'информатика'), ('physical education', 'физкультура'), ('german', 'немецкий'), ('russian', 'русский'), ('literature', 'литература'), ('social studies', 'Обществознание'), ('physics', 'физика'), ('art', 'искуство'), ('geography', 'география'), ('french', 'французский'), ('english', 'английский'), ('italian', 'итальянский'), ('biology', 'биология'), ('japanese', 'японский'), ('music', 'музыка'), ('math', 'математика')], max_length=50)),
                ('classes', models.CharField(max_length=50)),
                ('testQuestion', models.TextField(max_length=1000)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ('classes',),
            },
        ),
    ]
